#!/usr/bin/env bash

set -euo pipefail

[[ ${VERBOSE:-,,} =~ true|yes|on|1 ]] && set -x

LOCKFILE=/tmp/balena/updates.lock

while true; do
    (
        # request an exclusive lock in non-blocking mode
        flock -n 200 || exit 0

        # check for active sessions
        while last | grep -q "still logged in"; do

            echo "Updates are locked while sessions are active..."
            last | grep "still logged in"

            # wait 30 seconds before checking again
            # updates are locked during this time
            sleep 30
        done
    ) 200>$LOCKFILE

    # remove the lockfile
    # FIXME: why is this required when the lock is already released?
    rm -f $LOCKFILE

    # wait 5 seconds before checking again
    # updates are unlocked during this time
    sleep 5
done
