version: '2'

services:
  yocto-build-env:
    build: yocto-build-env
    privileged: true
    ports:
      - 22:22
    tmpfs:
      - /tmp
      - /run
    volumes:
      - home:/home
      - docker:/var/lib/docker
      - ssh:/etc/ssh

volumes:
  home: {}
  docker: {}
  ssh: {}
