version: '2'

services:
  yocto-build-env:
    build: yocto-build-env
    privileged: true
    ports:
      - 22:22
    tmpfs:
      - /tmp
      - /run
    volumes:
      - home:/home
      - docker:/var/lib/docker
      - ssh:/etc/ssh
      - sshd-logs:/var/log/sshd:rw

  # https://github.com/crazy-max/docker-fail2ban
  # https://hub.docker.com/r/crazymax/fail2ban/
  fail2ban:
    build: fail2ban
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - fail2ban:/data/db
      - sshd-logs:/var/log/sshd:ro
    environment:
      F2B_LOG_TARGET: STDOUT
      F2B_LOG_LEVEL: INFO
      F2B_DB_PURGE_AGE: 1w

volumes:
  home: {}
  docker: {}
  ssh: {}
  sshd-logs: {}
  fail2ban: {}
