# https://github.com/crazy-max/docker-fail2ban
# https://hub.docker.com/r/crazymax/fail2ban/
FROM crazymax/fail2ban:1.1.0@sha256:7cd8a427a44675397398a8dace2a3d755e62c72527f8730e4fd37697731a9321

COPY jail.d/ /data/jail.d/
