# https://github.com/crazy-max/docker-fail2ban
# https://hub.docker.com/r/crazymax/fail2ban/
FROM crazymax/fail2ban:1.1.0@sha256:a1476ec3587dd7c6756d8cdb448fb0a262c242042d8a71557da6b5aa7aecd911

COPY jail.d/ /data/jail.d/
