# https://github.com/crazy-max/docker-fail2ban
# https://hub.docker.com/r/crazymax/fail2ban/
FROM crazymax/fail2ban:1.0.2@sha256:3d33f7e528df372b5cdad85d86f8dec1156fdb442ccad82a2965a31c70233853

COPY jail.d/ /data/jail.d/
