#!/usr/bin/env bash

set -euo pipefail

[[ ${VERBOSE:-,,} =~ true|yes|on|1 ]] && set -x

exec 2>&1

mkdir -p /run/sshd

ssh-keygen -A

# run sshd in the foreground and format the logs such
# that fail2ban can parse them
exec /usr/sbin/sshd -De \
    -o "LogLevel=${SSHD_LOG_LEVEL:-INFO}" \
    -o PermitRootLogin=no \
    -o PasswordAuthentication=no \
    -o PubkeyAuthentication=yes \
    -o UsePAM=yes \
    -o AcceptEnv="LANG LC_*" \
    -o PrintMotd=no \
    -o Banner=none \
    -o StreamLocalBindUnlink=yes
