#!/usr/bin/env bash

set -euo pipefail

[[ ${VERBOSE:-,,} =~ true|yes|on|1 ]] && set -x

GH_HANDLES="${GH_HANDLES:-alexgg klutchell jakogut mtoman floion acostach majorz lmbarros}"

fetch_ssh_keys() {
    local _username="${1}"
    local _home="${2}"
    (
        cd "${_home}" || exit 1
        mkdir -p .ssh
        curl -fsSL "https://github.com/${_username}.keys" >>.ssh/authorized_keys
        chown -R "${_username}:${_username}" .ssh
        chmod -R 700 .ssh
    )
}

for username in ${GH_HANDLES:-}; do
    home="$(eval echo ~"${username}")"

    if [ -d "${home}" ]; then
        # create the user with the same uid as the existing home directory
        uid="$(stat -c "%u" "${home}")"
        adduser --disabled-password --gecos "${username}" "${username}" --uid "${uid}"
    else
        # create a new user and home directory
        adduser --disabled-password --gecos "${username}" "${username}"
    fi

    # add the user to the sudo and docker groups
    usermod -aG sudo "${username}" || true
    usermod -aG docker "${username}" || true

    # fetch the user's ssh keys from github
    fetch_ssh_keys "${username}" "${home}" || true
done
